/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated during migration — will be replaced with explicit
  // sidebar config once all content pages are migrated (Task 8+).
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
